---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedclusterrolebindings
  - timedrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedclusterrolebindings/finalizers
  - timedrolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedclusterrolebindings/status
  - timedrolebindings/status
  verbs:
  - get
  - patch
  - update
