# This rule is not used by the project k8s-timed-rolebinding itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to rbac.hhh.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-timed-rolebinding
    app.kubernetes.io/managed-by: kustomize
  name: timedclusterrolebinding-viewer-role
rules:
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedclusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedclusterrolebindings/status
  verbs:
  - get
