# This rule is not used by the project k8s-timed-rolebinding itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the rbac.hhh.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-timed-rolebinding
    app.kubernetes.io/managed-by: kustomize
  name: timedrolebinding-editor-role
rules:
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.hhh.github.io
  resources:
  - timedrolebindings/status
  verbs:
  - get
