apiVersion: rbac.hhh.github.io/v1alpha1
kind: TimedRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: k8s-timed-rolebinding
    app.kubernetes.io/managed-by: kustomize
  name: timedrolebinding-sample
spec:
  subjects:
    - kind: User
      name: user1
      apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: Role
    name: role1
    apiGroup: rbac.authorization.k8s.io
  startTime: 2025-01-01T06:00:00Z
  endTime: 2025-01-01T09:00:00Z
  keepExpiredFor: 1h
  postActivate:
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: post-activate
                image: busybox
                command: ["/bin/sh", "-c"]
                args: ["echo $TIMED_ROLE_BINDING_NAME has been activated"]
  postExpire:
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: post-expire
                image: busybox
                command: ["/bin/sh", "-c"]
                args: ["echo $TIMED_ROLE_BINDING_NAME has expired"]
