name: Release

on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hofman-tan/k8s-timed-rolebinding-operator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # grants write access to the release
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64 # TODO: multi-platform support
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  generate-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: false

      - name: Build installer manifest
        run: make build-installer IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ github.ref_name }}

      - name: Upload install.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/install.yaml
          asset_name: install.yaml
          tag: ${{ github.ref }}
          overwrite: true
